"""add attempts and telemetry events tables

Revision ID: a511bb307156
Revises: 01a3fc7c35de
Create Date: 2026-03-26 11:23:17.797523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a511bb307156'
down_revision: Union[str, None] = '01a3fc7c35de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('STARTED', 'SUBMITTED', 'PASSED', 'FAILED', 'TIMED_OUT', 'ABANDONED', name='attemptstatus'), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('test_cases_passed', sa.Integer(), nullable=True),
    sa.Column('test_cases_total', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_problem_status', 'attempts', ['problem_id', 'status'], unique=False)
    op.create_index('idx_started_at', 'attempts', ['started_at'], unique=False)
    op.create_index('idx_user_problem', 'attempts', ['user_id', 'problem_id'], unique=False)
    op.create_index('idx_user_status', 'attempts', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_attempts_id'), 'attempts', ['id'], unique=False)
    op.create_table('telemetry_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_since_start_ms', sa.Integer(), nullable=True),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_attempt_timestamp', 'telemetry_events', ['attempt_id', 'timestamp'], unique=False)
    op.create_index('idx_attempt_type', 'telemetry_events', ['attempt_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_telemetry_events_id'), 'telemetry_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_events_id'), table_name='telemetry_events')
    op.drop_index('idx_attempt_type', table_name='telemetry_events')
    op.drop_index('idx_attempt_timestamp', table_name='telemetry_events')
    op.drop_table('telemetry_events')
    op.drop_index(op.f('ix_attempts_id'), table_name='attempts')
    op.drop_index('idx_user_status', table_name='attempts')
    op.drop_index('idx_user_problem', table_name='attempts')
    op.drop_index('idx_started_at', table_name='attempts')
    op.drop_index('idx_problem_status', table_name='attempts')
    op.drop_table('attempts')
    # ### end Alembic commands ###
